source 'https://rubygems.org'

gem 'rake', '~> 10.0'
gem 'json-schema', '~> 2.5'

gem 'transitland_client', '0.0.5'

gem 'rspec', '~> 3.2'
gem 'simplecov', '~> 0.9'

gem 'pry', '~> 0.10'
gem 'byebug', '~> 4.0'
gem 'pry-byebug', '~> 3.1'
